# Example of extending a Posit product image to configure global pip settings.
#
# This pattern applies to any Posit product image (Connect, Workbench,
# Package Manager). Place pip.conf at /etc/pip.conf to set system-wide
# defaults for all pip invocations in the image.
#
# See: https://pip.pypa.io/en/stable/topics/configuration

### Specify the Posit product image to extend ###
ARG PWB_VERSION="2025.09.0"


### Extend the Posit Workbench Minimal image ###
FROM docker.io/posit/workbench:${PWB_VERSION}-min


### Add custom pip configuration ###
COPY pip.conf /etc/pip.conf
