# Example of extending a Posit Connect content image to pre-install R and
# Python packages.
#
# Connect content images are the runtime environment for off-host execution
# on Kubernetes. Baking packages into the content image means published
# content can import them without requiring a restore step at runtime.
# See: https://docs.posit.co/connect/admin/runtimes/content-images/

### Specify the Connect content image tag to extend ###
### Tag format: R{R_VERSION}-python{PYTHON_VERSION}-{OS}[-pro]          ###
### Full tag list: https://hub.docker.com/r/posit/connect-content        ###
ARG CONTENT_TAG="R4.5.2-python3.14.3-ubuntu-24.04-pro"


### Extend the Posit Connect content image ###
FROM ghcr.io/posit-dev/connect-content:${CONTENT_TAG}


### Install additional R packages from Posit Public Package Manager ###
COPY packages.txt /tmp/packages.txt
RUN /opt/R/4.5.2/bin/R --vanilla -e \
    'install.packages(readLines("/tmp/packages.txt"), repos="https://p3m.dev/cran/__linux__/noble/latest", clean = TRUE)'


### Install additional Python packages ###
COPY requirements.txt /tmp/requirements.txt
RUN /opt/python/3.14.3/bin/pip install --no-cache-dir --upgrade --break-system-packages \
    -r /tmp/requirements.txt
