{#-
Below are imports for Bakery's macros. If any are unneeded, they can be removed.
Bakery handles bootstrapping the files into template rendering.
-#}
{%- import "dnf.j2" as dnf -%}
FROM docker.io/library/rockylinux:9
LABEL org.opencontainers.image.base.name="docker.io/library/rockylinux:9"

### Install Dnf Packages ###
COPY {{ Path.Version }}/deps/{{ Image.OS.Name }}_packages.txt /tmp/packages.txt
{% if Image.Variant != "Minimal" -%}
COPY {{ Path.Version }}/deps/{{ Image.OS.Name }}_optional_packages.txt /tmp/optional_packages.txt
{% set package_files = ["/tmp/packages.txt", "/tmp/optional_packages.txt"] -%}
{% else -%}
{% set package_files = ["/tmp/packages.txt"] -%}
{% endif -%}
{{ dnf.run_install(files=package_files) }}
