FROM docker.io/library/rockylinux:9
LABEL org.opencontainers.image.base.name="docker.io/library/rockylinux:9"

### ARG declarations ###
ARG IMAGE_VERSION="1.0.0"

### Install Dnf Packages ###
COPY example-image/1.0.0/deps/rocky_packages.txt /tmp/packages.txt
RUN xargs -a /tmp/packages.txt dnf install -yq && \
    dnf clean all -yq
